apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imageclassifier1
  template:
    metadata:
      labels:
        app: imageclassifier1
    spec:
      containers:
      - name: cv-app
        image: gcr.io/nth-skyline-359108/imgwebapp:v1
        ports:
        - containerPort: 8501
